DROP TABLE IF EXISTS transacciones_diarias;
DROP TABLE IF EXISTS cuentas_con_interes;
DROP TABLE IF EXISTS estados_cuenta_anuales;

CREATE TABLE transacciones_diarias (
    id BIGINT PRIMARY KEY,
    fecha DATE NOT NULL,
    monto DECIMAL(15, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    anomalia BOOLEAN DEFAULT FALSE,
    observacion VARCHAR(255)
);

CREATE TABLE cuentas_con_interes (
    cuenta_id BIGINT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    saldo_inicial DECIMAL(15, 2) NOT NULL,
    edad INT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    tasa_interes DECIMAL(5, 4) NOT NULL,
    interes_calculado DECIMAL(15, 2) NOT NULL,
    saldo_final DECIMAL(15, 2) NOT NULL
);

CREATE TABLE estados_cuenta_anuales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id BIGINT NOT NULL,
    fecha DATE NOT NULL,
    transaccion VARCHAR(50) NOT NULL,
    monto DECIMAL(15, 2) NOT NULL,
    descripcion VARCHAR(255),
    clasificacion VARCHAR(50)
);
